### ISSUE TITLE
Just keeps on spamming error 1

### ISSUE THREAD

**Issue by AlexFiverr1** [DaveFeed/VK-Music-RPC-for-Discord#1]
Url: https://vk.com/id684002003
Choosen language: English
Added GitHub Button
Logging into client ...
Client is ready! Starting RPC. (Check Discord)
Error 1: This could resolve itself, lets wait and hope ...
Error 1: This could resolve itself, lets wait and hope ...
Error 1: This could resolve itself, lets wait and hope ...
Error 1: This could resolve itself, lets wait and hope ...
Error 1: This could resolve itself, lets wait and hope ...
Error 1: This could resolve itself, lets wait and hope ...
Error 1: This could resolve itself, lets wait and hope ...
Error 1: This could resolve itself, lets wait and hope ...

**Comment by AlexFiverr1** [comment]
![image](https://user-images.githubusercontent.com/95561131/144946956-53cc32fb-a45f-4a9e-9b10-798c8e9ff2a2.png)

**Comment by AlexFiverr1** [comment]
I changed my vk link to have "chillaussie" instead of that "id684002003" and it didn't seem to fix it.

**Comment by AlexFiverr1** [comment]
Fixed: Issue was due to me being in a different country which VK doesn't work in it was not able to connect, I got a vpn and the discord status worked.

**Comment by DaveFeed** [comment]
I was offline in github for a while, glad to hear that you fixed the issue. Sorry for not checking it in time. <3

**Comment by AlexFiverr1** [comment]
> I was offline in github for a while, glad to hear that you fixed the issue. Sorry for not checking it in time. <3

No problem, if you need anything or have any issues feel free to message me on discord: Hacks_Equals_Ban#8746
